// -*- C++ -*-
//
// generated by wxGlade 0.8.0a8 on Tue Nov 21 20:13:41 2017
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "MyFrame.h"

// begin wxGlade: ::extracode
// end wxGlade


MyFrame::MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    button_1 = new wxButton(this, wxID_ANY, wxT("button_1"));

    set_properties();
    do_layout();
    // end wxGlade
}


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("frame"));
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    sizer_6 = new wxBoxSizer(wxVERTICAL);
    sizer_6->Add(button_1, 0, 0, 0);
    SetSizer(sizer_6);
    sizer_6->Fit(this);
    Layout();
    // end wxGlade
}

